#Merge plugin should be configured
libraries:
  - 'com.zaxxer:HikariCP:5.0.0'
  - 'mysql:mysql-connector-java:8.0.27'
  - 'org.mariadb.jdbc:mariadb-java-client:3.4.1'
  - 'com.h2database:h2:2.2.224'
  - 'com.google.code.gson:gson:2.8.8'