# Merge into Bukkit plugin descriptors.
libraries:
  - 'com.zaxxer:HikariCP:${dep.hikari.version}'
  - 'mysql:mysql-connector-java:${dep.mysql.version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${dep.mariadb.version}'
  - 'com.h2database:h2:${dep.h2.version}'
  - 'com.google.code.gson:gson:${dep.gson.version}'
  - 'com.fasterxml.jackson.core:jackson-databind:${dep.jackson.databind.version}'
  - 'net.kyori:adventure-api:${adventure.version}'
  - 'net.kyori:adventure-key:${adventure.version}'
  - 'net.kyori:adventure-text-minimessage:${adventure.version}'
  - 'net.kyori:adventure-text-serializer-gson:${adventure.version}'
  - 'net.kyori:adventure-text-serializer-legacy:${adventure.version}'
  - 'net.kyori:adventure-text-serializer-plain:${adventure.version}'
  - 'net.kyori:adventure-platform-bukkit:${dep.adventure.platform.bukkit.version}'
softdepend:
  - ProtocolLib
  - PlaceholderAPI
  - Essentials
  - ShopGUIPlus
