# Merge into Bukkit plugin descriptors.
libraries:
  - 'com.zaxxer:HikariCP:${dep.hikari.version}'
  - 'mysql:mysql-connector-java:${dep.mysql.version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${dep.mariadb.version}'
  - 'com.h2database:h2:${dep.h2.version}'
  - 'com.google.code.gson:gson:${dep.gson.version}'
  - 'com.fasterxml.jackson.core:jackson-databind:${dep.jackson.databind.version}'
  - 'net.kyori:adventure-api:4.25.0'
  - 'net.kyori:adventure-key:4.25.0'
  - 'net.kyori:adventure-text-minimessage:4.25.0'
  - 'net.kyori:adventure-text-serializer-gson:4.25.0'
  - 'net.kyori:adventure-text-serializer-legacy:4.25.0'
  - 'net.kyori:adventure-text-serializer-plain:4.25.0'
  - 'net.kyori:adventure-platform-bukkit:${dep.adventure.platform.bukkit.version}'
softdepend:
  - ProtocolLib
